---
- name: Create Polkadot Validator systemd unit file
  hosts: polkadot-nodes
  become: yes

  vars:
    polkadot_bin_path: "/usr/local/bin/polkadot_v1.0.0.0"               # Path of the Polkadot bin location used during installation

  tasks:
    - name: Copying Jinja2 template for systemd unit file creation
      template:
        src: polkadot-validator.service.j2 
        dest: /etc/systemd/system/polkadot-validator.service            # destination path as specified in the Polkadot documentation
      notify: Reload systemd                                            # call the "reload systemd" handler after execution to reload the service.

  handlers:
    - name: Reload systemd
      systemd:
        name: polkadot-validator
        state: restarted                                                 # restart the polkadot-validator service